# Create an Array

In [1]:
# Create array with array module

In [2]:
import array

my_array = array.array("i") # O(1)
print(my_array)

my_array1 = array.array('i', [1,2,3,4]) # O(n)
print(my_array1)

array('i')
array('i', [1, 2, 3, 4])


In [3]:
# array creation using numpy module

In [4]:
import numpy as np
np_array = np.array([], dtype=int) # O(1)
print(np_array)

np_array1 = np.array([1,2,3,4]) # O(n)
print(np_array1)

[]
[1 2 3 4]


# Insertion to Array

In [5]:
import array

my_array1 = array.array('i', [1,2,3,4]) 
print(my_array1)
my_array1.insert(0, 6)
print(my_array1)

array('i', [1, 2, 3, 4])
array('i', [6, 1, 2, 3, 4])


In [6]:
import array

my_array1 = array.array('i', [1,2,3,4]) 
print(my_array1)
my_array1.insert(3, 6)
print(my_array1)

array('i', [1, 2, 3, 4])
array('i', [1, 2, 3, 6, 4])


# Traversal Operation

In [7]:
from array import *

In [8]:
arr1 = array("i", [1,2,3,4,5,6])
arr2 = array("d", [1.3, 1.5, 1.6])

In [9]:
def traversal(array):
    for i in array: # O(n)
        print(i) # O(1)

In [10]:
traversal(arr1)

1
2
3
4
5
6


# Accessing an element of Array

In [11]:
arr1 = array("i", [1,2,3,4,5,6])

In [12]:
def accessElement(array, index):
    if index >= len(array):
        print("there is not any element in this index")
    else:
        print(array[index])

In [13]:
accessElement(arr1, 3)

4


# Searching for an Element

In [14]:
arr1 = array("i", [1,2,3,4,5,6])

In [15]:
def linear_search(arr, target):
    for i in range(len(arr)): # O(n)
        if arr[i] == target:
            return i # O(1)
    return "Sorry" # O(1)

In [16]:
print(linear_search(arr1, 8))

Sorry


# Deleting an Element from Array

In [17]:
arr1 = array("i", [1,2,3,4,5,6])

In [18]:
arr1.remove(3)

# if remving from last then O(1)
# if we remove from middle or something then O(n)

print(arr1)

array('i', [1, 2, 4, 5, 6])


# One Dimensional Array Practice

In [19]:
arr = array('i', [1,2,3,4,5])

In [20]:
for i in arr:
    print(i)

1
2
3
4
5


In [21]:
arr[1]

2

In [22]:
arr.append(6)

In [23]:
arr

array('i', [1, 2, 3, 4, 5, 6])

In [24]:
# insert
arr.insert(3, 10)

print(arr)

array('i', [1, 2, 3, 10, 4, 5, 6])


In [25]:
# extend
my_array1 = array('i', [10,11,12])
arr.extend(my_array1)
print(arr)

array('i', [1, 2, 3, 10, 4, 5, 6, 10, 11, 12])


In [26]:
# add items from list
arr = array('i', [1,2,3,4,5])

list = [20,30, 40]
arr.fromlist(list)
print(arr)

array('i', [1, 2, 3, 4, 5, 20, 30, 40])


In [27]:
# remove last array

arr.pop()
print(arr)

array('i', [1, 2, 3, 4, 5, 20, 30])


In [28]:
#index of array
print(arr.index(20))

5


In [29]:
#reverse array

arr.reverse()
arr

array('i', [30, 20, 5, 4, 3, 2, 1])

In [30]:
# buffer info

arr.buffer_info()

(140585476870752, 7)

In [31]:
arr.count(2)

1

In [38]:
# converting array to list

list = arr.tolist()
print(list)

[30, 20, 5, 4, 3, 2, 1]


In [39]:
# slicing
arr[1:3]

array('i', [20, 5])

In [40]:
arr[:2]

array('i', [30, 20])

In [41]:
arr[2:]

array('i', [5, 4, 3, 2, 1])

# Create two dimensional array

In [1]:
import numpy as np

In [74]:
twoDArray = np.array([[11, 12, 23, 5], [2, 3, 4, 5], [9, 7, 90, 6]])

In [75]:
twoDArray

array([[11, 12, 23,  5],
       [ 2,  3,  4,  5],
       [ 9,  7, 90,  6]])

In [65]:
# Insertion of column at the beginning

newTwoDarray = np.insert(twoDArray, 0, [[1, 2, 3]], axis=1) # coulmun means axis 1

In [66]:
newTwoDarray

array([[ 1, 11, 12, 23,  5],
       [ 2,  2,  3,  4,  5],
       [ 3,  9,  7, 90,  6]])

In [67]:
# Insertion of column at the beginning

newTwoDarray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=0) # coulmun means axis 1

In [68]:
newTwoDarray

array([[ 1,  2,  3,  4],
       [11, 12, 23,  5],
       [ 2,  3,  4,  5],
       [ 9,  7, 90,  6]])

In [69]:
# if we want to add at the middle

addmiddle = np.insert(twoDArray, 2, [[0, 0, 0, 0]], axis=0) # coulmun means axis 1
addmiddle

array([[11, 12, 23,  5],
       [ 2,  3,  4,  5],
       [ 0,  0,  0,  0],
       [ 9,  7, 90,  6]])

In [70]:
# using append

addmiddle = np.append(twoDArray, [[0, 0, 0, 0]], axis=0) # coulmun means axis 1
addmiddle

array([[11, 12, 23,  5],
       [ 2,  3,  4,  5],
       [ 9,  7, 90,  6],
       [ 0,  0,  0,  0]])

# Access two dimensional array

In [ ]:
# first have to identify row
# then column index 

In [78]:
def accessElements(array, rowindex, colindex):
    if rowindex >= len(array) and colindex >= len(array[0]): # O(1)
        print("Incorrect Index") # O(1)
    else:
        print(array[rowindex][colindex]) # O(1)

In [79]:
accessElements(twoDArray, 1, 2)


4


# Traversal two dimensional array

In [6]:
twoDArray = np.array([[11, 12, 23, 5], [2, 3, 4, 5], [9, 7, 90, 6]])

In [4]:
def traverseTdarraay(array):
    for i in range(len(array)): # O(mn)
        for j in range(len(array[0])): # O(n)
            print(array[i][j]) # O(1)

In [5]:
traverseTdarraay(twoDArray)

11
12
23
5
2
3
4
5
9
7
90
6


# Searching

In [10]:
def searchTDA(array, value):
    for i in range(len(array)): # O(mn)
        for j in range(len(array[0])): # O(n)
            if array[i][j] == value: # O(1)
                return "The value is located "+str(i)+" "+str(j)
    return "the element is not found"
    

In [11]:
searchTDA(twoDArray, 2)

'The value is located 1 0'

# Deletion

In [12]:
newTD = np.delete(twoDArray, 0, axis=1)

In [13]:
newTD

array([[12, 23,  5],
       [ 3,  4,  5],
       [ 7, 90,  6]])